---
- name: run pre-reqs
  gather_facts: no
  hosts: PSM

  tasks:
    - name: ping
      win_ping:
      vars: 
        ansible_winrm_server_cert_validation: ignore

    - name: trigger ansible Copy File
      import_role:
        name: ansible-copy-file
          
    - name: trigger ansible unzip code  
      import_role:
        name: ansible-unzip
        
    - name: install dotNet 4.7.2
      import_role:
        name: install-package
       
    - name: trigger ansible psm role
      import_role:
        name: ansible-role-psm
        
#     - Deploy PSM Health Check

#     - copy Connectors

#     - copy third party software binaries
#     - install third party applications
#     - copy Config Files (Applocker, Hardening)
#     - Trigger Powershell Applocker Run
#     - Trigger Powershell Hardening Run


#     - Idea: whenever a connector is getting deployed, trigger API Calls (win_uri) to create Users in ITPA, based on the connector testing or needs.
        
      vars:
        psm_prerequisites: false
        psm_install: false
        psm_postinstall: false
        psm_hardening: false
        psm_registration: true
        ps_clean: false
        vault_ip: 10.128.240.86
        vault_username: administrator
        vault_password: "{{ lookup('env', 'VMWARE_PASSWORD') }}"
        accept_eula: yes
        psm_zip_file_path: 'E:\Upgrade2021\Privileged Session Manager-Rls-v12.0.zip'
        connect_with_rdp: No
        psm_installation_drive: 'F:'
        psm_out_of_domain: true
        psm_extract: false
