---
ansible_connection: winrm
ansible_winrm_port: 5986
ansible_winrm_scheme: https
ansible_winrm_transport: basic
ansible_winrm_server_cert_validation: ignore
#ansible_winrm_ca_trust_path: /etc/pki/ca-trust/extracted/openssl/ca-bundle.trust.crt
